# Generated by Django 5.1.6 on 2025-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='signup_date',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-05 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
